### ISSUE TITLE
Mat_CreateVer and Mat_Open do not support unicode (wstring) filename on windows

### ISSUE THREAD

**Issue by Nelson-numerical-software** [tbeu/matio#105]
Mat_CreateVer and Mat_Open do not support wchar_t* as filename

```
A = 1:10
save('d:/漢字.mat')
clear
load('d:/漢字.mat')
```

**Comment by tbeu** [comment]
Confirmed. Unfortunately, there neither is a wide-tring equivalent of [H5Fcreate](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5F.html#File-Create) nor [H5Fopen](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5F.html#File-Open). Please see also [here](https://forum.hdfgroup.org/t/h5fcreate-and-h5fopen-with-chinese-filename-wide-char/1450) or contact the HDF Group with your requirement. Once the hdf5 C library supports wide-string file names, I can extend matio to also support it consistenly.

**Comment by Nelson-numerical-software** [comment]
not only hdf5, same problem with v6, or others

**Comment by tbeu** [comment]
I know. That's why I wrote _consistenly_ = for all versions.

**Comment by Nelson-numerical-software** [comment]
reported on HDF5 forum:
https://forum.hdfgroup.org/t/h5fcreate-and-h5fopen-with-chinese-filename-wide-char/1450/5

**Comment by tbeu** [comment]
Should be possible by 6d47ebd4bb1186a737f895848009de1e317f9962. For v7.3 MAT files you'll need the next major HDF5 version (the one after 1.12.x due in September).

By the way, it already was working correctly in Cygwin, but I guess you meant MSVC when you said windows.

**Comment by Nelson-numerical-software** [comment]
Sorry to ask here but it is not clear in release notes of hdf5 library, does it already released in an official hdf5 library released or not ? 
last official hdf5 library 1.10.6
https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_10_6/source/hdf5-1.10.6-RELEASE.txt?utm_source=HDF+Group+Contacts&utm_campaign=248761b238-HDF5+1.10.6+Release+%28Newsletter+%23170%29&utm_medium=email&utm_term=0_60afc5d864-248761b238-212404827

**Comment by Nelson-numerical-software** [comment]
> Sorry to ask here but it is not clear in release notes of hdf5 library, does it already released in an official hdf5 library released or not ?
> last official hdf5 library 1.10.6
> https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_10_6/source/hdf5-1.10.6-RELEASE.txt?utm_source=HDF+Group+Contacts&utm_campaign=248761b238-HDF5+1.10.6+Release+%28Newsletter+%23170%29&utm_medium=email&utm_term=0_60afc5d864-248761b238-212404827

It will be available in 1.12
current branch is only alpha stage ...
https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/release_docs/HISTORY-1_10_0-1_12_0.txt?at=refs%2Fheads%2Fhdf5_1_12

**Comment by tbeu** [comment]
Yes, there is not yet a released hdf5 library version.

**Comment by Nelson-numerical-software** [comment]
hdf5 1.12 is available.
A matio release with official support could be great.
It seems that vs project (matio) need to be updated (zlib.h not found) for hdf5 1.12
but zlib.h is available in CMake-hdf5-1.12.0-x64\build\ZLIB-prefix\src\ZLIB

**Comment by Nelson-numerical-software** [comment]
hdf5 1.14.6 fix a regression about this trouble
https://github.com/HDFGroup/hdf5/issues/4599
