### ISSUE TITLE
submit matio to conan-center

### ISSUE THREAD

**Issue by vincent-hui** [tbeu/matio#122]
I think it is convenient for users if matio can be installed via conan package manager.

Would you mind submitting matio to conan-center?

**Comment by Nelson-numerical-software** [comment]
brew and debian packages (ppa) should be considered based on standard hdf5 dependency

**Comment by tbeu** [comment]
I have no clue what I shall be done here since I never used conan-center.

**Comment by vincent-hui** [comment]
@tbeu You can follow the guide https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html
It seems it is not too difficult.
It would be great if you can submit matio to conan-center.
Thank you very much.

**Comment by tbeu** [comment]
I accept PRs 😄

**Comment by tbeu** [comment]
```shell
$ conan search matio -r conan-center
Existing package recipes:

matio/1.5.18
```
