### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [tbeu/matio#124]
Greetings matio developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can attach our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by tbeu** [comment]
Running the fuzzer is not a big deal, but analyzing and fixing may take a huge effort. I still have many crafted files here when I run honggfuzz 1.8 (through Cygwin) occasionally.

**Comment by Google-Autofuzz** [comment]
> Running the fuzzer is not a big deal, but analyzing and fixing may take a huge effort. I still have many crafted files here when I run honggfuzz 1.8 (through Cygwin) occasionally.

Do you prefer us to attach our internal fuzz target here first and you can integrate it after you done crafting the files? Or do you prefer us to integrate it to OSS-Fuzz as a starting point? If we do the integration for you, can you please provide an @gmail.com email address, so that you can get access to OSS-Fuzz's dashboard and get notified of the crashes?

**Comment by tbeu** [comment]
If you like you can start the integration. However, I do not have a gmail address, but you can contact me via https://github.com/tbeu/matio#11-contact.

**Comment by Google-Autofuzz** [comment]
> If you like you can start the integration. However, I do not have a gmail address, but you can contact me via https://github.com/tbeu/matio#11-contact.

Sure. Can you provide a google/gmail address so that you can open up to see bugs/crashes after integration?

**Comment by tbeu** [comment]
@Google-Autofuzz How should reference your created issues when providing a fix? Is is enough to reference the issue number (e.g., Issue 16833) in the commit message?

**Comment by Google-Autofuzz** [comment]
> @Google-Autofuzz How should I reference your created issues when providing a fix? Is is enough to reference the issue number (e.g., Issue 16833) in the commit message? Or do you want me also to edit your issues at https://bugs.chromium.org/p/oss-fuzz ?

You should ask the [OSS-Fuzz team](https://github.com/google/oss-fuzz/issues) about this since they are the ones that create the issues. But, before you fix the bugs, you should try to reproduce the issues (see https://google.github.io/oss-fuzz/advanced-topics/reproducing/).

**Comment by tbeu** [comment]
Not sure how and whom should I ask there. I read the FAQs but this was not addressed.

**Comment by tbeu** [comment]
Currently the fuzzed files are all v4 MAT files. How can we create fuzzed v5 files?

**Comment by Google-Autofuzz** [comment]
OSS-Fuzz will automatically close the issues when the underlying cause is fixed upstream.

As for the version of MAT files, since the fuzzer is coverage based, if there is a way to parse v5 files via the api used by the [fuzzer]( https://github.com/google/oss-fuzz/blob/master/projects/matio/matio_fuzzer.cc ), odds are that they will be exercised at some point.

**Comment by tbeu** [comment]
OK.

Can we close this issue then?

**Comment by Google-Autofuzz** [comment]
Absolutely :)

Feel free to reach out if you have more questions, we're happy to help

**Comment by tbeu** [comment]
Thanks.

I noticed that the matio used for fuzzing is not built with hdf5 support. Should that be improved?

**Comment by Google-Autofuzz** [comment]
Feel free to open a pull-request to improve it :)

**Comment by tbeu** [comment]
Done.

How can I force (earlier) that a new version is built whenever I push commits? Currently it takes up to 2 days till I get the response.

**Comment by tbeu** [comment]
> As for the version of MAT files, since the fuzzer is coverage based, if there is a way to parse v5 files via the api used by the [fuzzer](https://github.com/google/oss-fuzz/blob/master/projects/matio/matio_fuzzer.cc), odds are that they will be exercised at some point.

Yes, if byte 0x7d of the input file stream is 0x00 and byte 0x7e is 0x01 or 0x02. So far (after one week of running) this what not yet the case, though 16 issues on v4 MAT files have been found.

**Comment by Google-Autofuzz** [comment]
I don't understand what you mean by "How can I force (earlier) that a new version is built whenever I push commits? Currently it takes up to 2 days till I get the response."

You can [add a corpus]( https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus ) if you want to help the fuzzer discover new paths more quickly.
