### ISSUE TITLE
How to save matrices by row-first method ?

### ISSUE THREAD

**Issue by onurcanbektas** [tbeu/matio#126]
Let say I have the matrix 

`h[4] = {{1,2},{3,4}};`

If I tried to save this *.mat file, the saved matrix will be 

`[1,3;2,4] `

in MATLAB. However, I would like to save it in such a way that, in MATLAB the saved matrix will also be 

`[1,2;3,4]`

How can I do that ?

**Comment by tbeu** [comment]
Have a look at https://sourceforge.net/p/matio/feature-requests/4/.
