### ISSUE TITLE
It's very slow if import one cell

### ISSUE THREAD

**Issue by an-ttt** [tbeu/matio#140]
I have a MAT_C_CELL type variable with large amount of cells.
I want to import one cell in it.
It's very slow because matio will read all the cells even if I want only one cell.
It's the same problem with MAT_T_STRUCT type too.
Could you help to fix it?

**Comment by Nelson-numerical-software** [comment]
could you provide an example or a script to create cell or struct to reproduce this trouble ?

**Comment by tbeu** [comment]
Closing as issue author did not provide full information for reporduction.
