### ISSUE TITLE
Reading sparse array - invalid number of elements

### ISSUE THREAD

**Issue by addroz** [tbeu/matio#156]
Hi,

I read a MAT file using matio, and casting the data to `mat_sparse_t` seems to work wrong. The sparse array has 632 non-empty elements, but the value of `nir` field is 641. Is that a bug or I do sth wrong? I attach the test

[mathworks100.zip](https://github.com/tbeu/matio/files/5283176/mathworks100.zip)

**Comment by tbeu** [comment]
Confirmed, but 641 is the number obtained from the file. If I load your MAT file and save it again in MATLAB R2109a, I get the expected numbers when reading in matio: [T156.zip](https://github.com/tbeu/matio/files/5284812/T156.zip). To me it looks like an issue in the MATLAB version you saved the variables A and U.
