### ISSUE TITLE
Install on Linux: How to install with reduced permissions (both CMake and Autotools)

### ISSUE THREAD

**Issue by tbeu** [tbeu/matio#162]
@MaartenBent @sjoelund @dietmarw There was an issue/question about how to build/install matio with reduced permissions, see https://sourceforge.net/p/matio/discussion/609377/thread/57ef76e338/ Do you think you can give him advice? Feel free to reply here or on SF.net. Thank you.

**Comment by emmenlau** [comment]
I have just answered with:

Is it possible that you did not set an install target directory? With autotools (configure), this is typically performed with the option `--prefix=/some/directory/where/you/can/write`, and with cmake its done via `-DCMAKE_INSTALL_PREFIX=/some/directory/where/you/can/write`

**Comment by tbeu** [comment]
Thank you at @emmenlau . It just was too obvious.
