### ISSUE TITLE
compression field not populated when reading MAT v7.3 variable info

### ISSUE THREAD

**Issue by rafal-c** [tbeu/matio#166]
Consider matio test file `matio/test/datasets/matio_test_cases_compressed_hdf_le.mat`. `h5dump` for this file shows
```
DATASET "var70" {
      ...
      FILTERS {
         COMPRESSION DEFLATE { LEVEL 3 }
      }
      ...
```
meaning that the variable is compressed, but if you open this variable with `Mat_VarReadInfo` the `compression` field in the `matvar` structure is set to `MAT_COMPRESSION_NONE`.

**Comment by tbeu** [comment]
Resolved by ffaf07e by using var70 of matio_test_cases_compressed_hdf_le.mat as test.
