### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SDMProjects** [tbeu/matio#169]
I try to generate the user guide in PDF format with the cmd line : matio_user_guide.texi

**Comment by SDMProjects** [comment]
I try to generate the user guide in PDF format with the cmd line : texi2pdf matio_user_guide.texi matio_user_guide.pdf

I have the following error :
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdfetex)
 restricted \write18 enabled.
entering extended mode
(./matio_user_guide.pdf
./matio_user_guide.pdf:9: Misplaced alignment tab character &.

**Comment by dietmarw** [comment]
I just tested it on two machines (with the same TeX live version: 
`This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdfetex)`) and it works fine. 
So maybe an issue in the older TeX Live version?

**Comment by tbeu** [comment]
Call `texi2pdf matio_user_guide.texi -o matio_user_guide.pdf` instead.
