### ISSUE TITLE
how to use matio in ubuntu version clion?

### ISSUE THREAD

**Issue by Daniel-Ming** [tbeu/matio#177]
I've successfully installed the matio package in my ubuntu 18 and when I use #include<matio.h> in clion, it can find the content but when I build my project , the build process failed, showing that Mat_Open is not defined in the main script. I think maybe a find_package() command in the CMakeLists.txt should added to locate this matio package but I have no idea how to do that.

**Comment by tbeu** [comment]
Please give full information (CMake command line) how you installed matio.
