### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by aminya** [tbeu/matio#185]
I see there are a lot of changes since the last release. Is there a plan for tagging a new release?
https://github.com/tbeu/matio/compare/v1.5.21...master

**Comment by tbeu** [comment]
Yes, it is about time. Still want to have #176 solved before a new release.

**Comment by tbeu** [comment]
[v1.5.22](https://github.com/tbeu/matio/releases/tag/v1.5.22) is released.
