### ISSUE TITLE
Mat_VarReadNextInfoIterate takes a long time to read mat-file

### ISSUE THREAD

**Issue by GolubevaP** [tbeu/matio#196]
Reading the header by indexes takes a lot of time (several minutes), moreover, it requires a lot of memory to read it. Although this is only needed to make sure that the file can be opened.
I realized that the problem is in this method (Mat_VarReadNextInfoIterate), in particular, in nested loops. And also this problem met earlier (https://github.com/tbeu/matio/issues/157). Will you fix it?

**Comment by Ri0n** [comment]
Hello dear developers.

This PR https://github.com/tbeu/matio/pull/197 partially resolves the problem.
But the root of the problem is hidden in usage of `H5Iget_name` which is extremely slow.

**Comment by Ri0n** [comment]
And there is a PR for avoiding usage of H5Iget_name
https://github.com/Ri0n/matio/pull/1/files

**Comment by Ri0n** [comment]
A PR for `H5Iget_name` against this repo https://github.com/tbeu/matio/pull/198
I'm very worried if I could break anything with this change. So I hope developers can propose appropriate tests and teest it on their own.

**Comment by tbeu** [comment]
@Ri0n Thanks for both your PRs. They are very appreciated.

**Comment by tbeu** [comment]
@GolubevaP Which MAT-file version did you use? Do you have any MAT-file to share? Thanks.

**Comment by tbeu** [comment]
> @GolubevaP Which MAT-file version did you use? Do you have any MAT-file to share? Thanks.

@GolubevaP Since #157 is fixed and @Ri0n contributed his fixes, can you please test again. Thanks!

**Comment by tbeu** [comment]
Closing after @GolubevaP not responding.
