### ISSUE TITLE
Request for using test data

### ISSUE THREAD

**Issue by pantxo** [tbeu/matio#204]
Hello,
Many thanks for your work.

I'd like to use matio's hdf5 datasets to test[ an implementation of Matlab's interface to HDF5](https://github.com/pantxo/oct-hdf5) including v7.3 format mat files. Can I add the dataset submodule to my repo?  Thanks.
  
Sorry for using the issue tracker for this request that is not an actual matio issue, but I didn't know how to contact the matio maintainers.

**Comment by tbeu** [comment]
Yes, you can use the test files as you like. They are available from https://sourceforge.net/p/matio/matio_test_datasets/ci/master/tree/ .

**Comment by pantxo** [comment]
Many thanks for your reply, I added the submodule with [this changeset](https://github.com/pantxo/oct-hdf5/commit/03bab26b982dcb1d05046cb79fc3bc80ea429c53).

**Comment by tbeu** [comment]
https://github.com/tbeu/matio/blob/master/.gitmodules uses some different url, but I guess both cases are valid.

**Comment by pantxo** [comment]
At least that url seams to work for me.
