### ISSUE TITLE
Not able to build on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by Ananyaaynana** [tbeu/matio#207]
I am trying to build matio library in Ubuntu 22.04.2 LTS using these steps:
1) I downloaded the master branch from github.
2) I unzipped it and went into the matio-master home directory.
3) On the terminal I ran the command ./configure
I received this error:
ananya@ananya-Latitude-7480:~/matio-master$ ./configure
bash: ./configure: No such file or directory
So I installed autoconf and ran this command
4)$ autoconf configure.ac
I got this error:
configure.ac:34: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:36: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:126: error: possibly undefined macro: AC_ENABLE_SHARED
configure.ac:127: error: possibly undefined macro: AC_ENABLE_STATIC
configure.ac:224: error: possibly undefined macro: AC_TYPE_OFF64_T
configure.ac:232: error: possibly undefined macro: AC_CHECK_VA_COPY
configure.ac:326: error: possibly undefined macro: AM_CONDITIONAL
Impact: Not able to proceed with reading the .mat file

**Comment by tbeu** [comment]
Please install [libtool](https://packages.ubuntu.com/jammy/libtool) and run `./autogen.sh` (as documented in https://github.com/tbeu/matio#221-quick-build-guide).
