### ISSUE TITLE
cmake can not verify HDF5 version when building with VS 2022 

### ISSUE THREAD

**Issue by jsemeda** [tbeu/matio#219]
Building the code with VS 2022, when I run cmake with cmakelists I get an error that it can not verify that the HDF5 version is higher then 1.8, it displays an empty version number " ". I removed that line from the thirdParties.cmake file, line #26, and it built.
However when I add the HDF5 libraries to matio to build I get unresolved externals on all HDF5 functions. I am using a static linking project.

**Comment by tbeu** [comment]
Please provide the full output of teh CMake command. Whch CMake version did you use?
