### ISSUE TITLE
Methods to access data stored in nested variables in.mat file.

### ISSUE THREAD

**Issue by droid-hunter** [tbeu/matio#220]
I am trying to access the data which is present in nested variables in my .mat file (version 256).

1. At the top level, there is a variable named "Stock," which is of type 1x1 struct.
2. Under the "Stock" variable, I have two sub-variables: "Alpha," "Beta," which are also 1x1 structures.
3. Under "Alpha," I have two more variables: "A1," "A2,"each containing data stored in matrices of 100x20 uint8, 100x1 logical respectively.
4. Similarly, "Beta" contains "B1," "B2," with data stored in matrices of 100x20 single, 100x20 uint16 respectively.

My objective is to extract the data stored in variables A1, A2, B1, B2,
It appears that the Mat_VarRead() method works effectively when dealing with data at a single level without nested variables (or correct me if I'm wrong).

Please guide on suitable MatIO methods/sample code for the same.

**Comment by Nelson-numerical-software** [comment]
@tbeu can give maybe a simple example.

You can find here how a mat struct is loaded in Nelson using matio:
https://github.com/Nelson-numerical-software/nelson/blob/master/modules/matio/src/cpp/LoadMatioStruct.cpp
