### ISSUE TITLE
Use of 'extern "C"' and MATIO_NORETURN in C++ build

### ISSUE THREAD

**Issue by gsjaardema** [tbeu/matio#23]
There seems to be some strange interaction of the use of MATIO_NORETURN and EXTERN when building a C++ code on mac and linux.

If I use `EXTERN MATIO_NORETURN void   Mat_Error( const char *format, ... )` on the Mac it works.  The reverse 'MATIO_NOTRETURN EXTERN` fails as does having the `MATIO_NORETURN` on a separate line. This is with g++-5.3.0

This ordering also works on my linux system using g++-5.2.0.

A related issue is that g++-4.7.2 seems to define __cplusplus >= 201103L even though it doesn't support the [[noreturn]].  This wasn't supported until g++-4.8. 

I think that one fix is to change the ordering to 'EXTERN MATIO_NORETURN' in matio.h

Not sure what the fix is for the [[noreturn]] issue; just opening it up for discussion.

**Comment by tbeu** [comment]
@sjoelund The [[noreturn]] case was copied from ModelicaUtilities.h. Can you please inspect and comment on it. Thanks.

**Comment by sjoelund** [comment]
Yes, I think for C++, extern "C" needs to be the first part of the declaration. It's more conceptual to extern "C" { declaration }, whereas in C, extern is just a part of the declaration. It did work with clang++ -std=c++11 and g++ with default std; only breaks with g++ -std=c++11.

**Comment by tbeu** [comment]
I hopefully fixed the C++ compilation in branch fix-c++. Please test and confirm if it works for you.

**Comment by gsjaardema** [comment]
Yes, works for me. Thanks.

**Comment by tbeu** [comment]
Fixed by 07728a38d99ee0a3f5b7685dcb18033d76947560.
