### ISSUE TITLE
CAN it replace or just input one column date？

### ISSUE THREAD

**Issue by XinmengZeng** [tbeu/matio#253]
Dear developer,

         I want to write some date into one matrix in different timestep, it means that for one step, i just only input one column in the matrix, but i found that, it is can not work, once whole matrix entry the mat file, the date can not replace if rewrite it, it can not wirte just one by one line.
        
        Hope to get help!

best
Xinmeng

**Comment by tbeu** [comment]
MatIO is not designed for your use case. You rather would need to read the variable, delete the variable from file (Mat_VarDelete), update the read vaiable and write back.

**Comment by tbeu** [comment]
I consider this answered.

**Comment by tbeu** [comment]
There is Mat_VarWriteAppend actually:

> Optionally, a variable can be appended to an existing variable of an HDF5 format MAT file
> by the Mat_VarWriteAppend function, which takes the same arguments as Mat_VarWrite as the
> first three arguments and the dimension as fourth argument. The dimension argument is index
> 1 based, i.e., if it is set to d, the variable is appended along the d-th dimension. If a variable
> is to be created for later appending, it always must be written by the Mat_VarWriteAppend function
> and Mat_VarWrite must not be called.
