### ISSUE TITLE
After make command get this error: missing binary operator before token "(" 

### ISSUE THREAD

**Issue by ShiGongCai** [tbeu/matio#254]
mat.c: In function ‘Mat_Open’:
mat.c:631:18: error: missing binary operator before token "("
  631 | #if H5_VERSION_GE(1, 10, 2)
  how to solver this?

**Comment by tbeu** [comment]
Can you please give the complete compiler output such that I also know your compiler name, version, OS and matio settings for MAT73 and HDF5?

**Comment by tbeu** [comment]
Closing then.
