### ISSUE TITLE
Compiles fine on OSX but all tests fail

### ISSUE THREAD

**Issue by 183amir** [tbeu/matio#26]
Hi,

I have been trying to package this program for [conda](http://conda.pydata.org/docs/index.html) but all tests fail after I compile this on travis osx:
https://travis-ci.org/bioidiap/bob.conda/jobs/112988995

Do you have any idea what goes wrong?

You can see my conda recipe here:
https://github.com/bioidiap/bob.conda/tree/master/libmatio

I ran this on my mac and here is the log:
[testsuite.txt](https://github.com/tbeu/matio/files/157014/testsuite.txt)

**Comment by tbeu** [comment]
Sorry, I have no idea, but it should work on OSX, see https://travis-ci.org/tbeu/matio

**Comment by 183amir** [comment]
Yes it should work but all tests are failing with an error like this:

    #                             -*- compilation -*-
    1. mat4_read_le.at:29: testing Read 2d double-precision array ...
    ./mat4_read_le.at:31: $builddir/test_mat readvar $srcdir/datasets/matio_test_cases_v4_le.mat var1
    --- /dev/null	2016-03-03 15:55:59.000000000 +0100
    +++ /Users/travis/miniconda/conda-bld/work/matio-1.5.6/test/testsuite.dir/at-groups/1/stderr	2016-03-03 15:55:59.000000000 +0100
    @@ -0,0 +1,4 @@
    +dyld: Library not loaded: @rpath/./libhdf5.10.dylib
    +  Referenced from: /Users/travis/miniconda/conda-bld/work/matio-1.5.6/test/.libs/test_mat
    +  Reason: image not found
    +/Users/travis/miniconda/conda-bld/work/matio-1.5.6/test/testsuite.dir/at-groups/1/test-source: line 54: 37108 Trace/BPT trap: 5       $builddir/test_mat readvar $srcdir/datasets/matio_test_cases_v4_le.mat var1
    --- -	2016-03-03 15:55:59.000000000 +0100
    +++ /Users/travis/miniconda/conda-bld/work/matio-1.5.6/test/testsuite.dir/at-groups/1/stdout	2016-03-03 15:55:59.000000000 +0100
    @@ -1,12 +1 @@
    -      Name: var1
    -      Rank: 2
    -Dimensions: 4 x 5
    -Class Type: Double Precision Array
    - Data Type: IEEE 754 double-precision
    -{
    -1 5 9 13 17 
    -2 6 10 14 18 
    -3 7 11 15 19 
    -4 8 12 16 20 
    -}
     
    ./mat4_read_le.at:31: exit code was 133, expected 0
    1. mat4_read_le.at:29: 1. Read 2d double-precision array (mat4_read_le.at:29): FAILED (mat4_read_le.at:31)

**Comment by tbeu** [comment]
You might try to build matio w/o hdf5 support.

**Comment by tbeu** [comment]
Maybe, this one helps: http://stackoverflow.com/questions/28244468/dyld-library-not-loaded-rpath-with-ios8

**Comment by 183amir** [comment]
My problem is probably related to issues mentioned here:
https://github.com/ContinuumIO/anaconda-issues/issues/598
https://github.com/conda/conda-build/issues/279
https://github.com/conda/conda-build/pull/312

**Comment by 183amir** [comment]
MAT IO compiles fine with hdf5 from system but not with the one that is in conda.

**Comment by tbeu** [comment]
Sorry, can't help (further). Neither I have OSX experience nor an idea what conda is.

**Comment by tbeu** [comment]
Nothing I can do here. Sorry.

**Comment by 183amir** [comment]
Is there a way that I could install the test files with `make install` and test the library after it is packaged in `conda`. Since conda does some library path manipulation after you install the package.
