### ISSUE TITLE
[MATIO 1.5.6] testsuite fails with hdf5 error

### ISSUE THREAD

**Issue by 183amir** [tbeu/matio#33]
I don't know what changed, it was working before.
[testsuite.log](https://github.com/tbeu/matio/files/196411/testsuite.txt)

**Comment by tbeu** [comment]
What do you mean by "it was working before."? Which version exactly?

**Comment by tbeu** [comment]
And which version of libhdf5 do you use? The `HDF5 error`s should not be there at all. It's all about them.

**Comment by 183amir** [comment]
The same `matio` version.

**Comment by 183amir** [comment]
`hdf5:     1.8.16-0`

**Comment by tbeu** [comment]
Maybe it has to do with the HDF5 filter plugins. Check section 4.4 of https://www.hdfgroup.org/HDF5/doc/Advanced/DynamicallyLoadedFilters/HDF5DynamicallyLoadedFilters.pdf and what your hdf5 config header / env var has set for as filter directory.

**Comment by tbeu** [comment]
Ah, is the test error reproducable?

**Comment by 183amir** [comment]
Yes

**Comment by 183amir** [comment]
Thank you. Looks like my hdf5 is built without zlib.

**Comment by jakirkham** [comment]
Feel free to close this out. It appears related to an issue building HDF5 where zlib was not getting picked up during the build. Correcting that issue appears to have resolved this one.
