### ISSUE TITLE
size of mat file grows on successive calls

### ISSUE THREAD

**Issue by kupiqu** [tbeu/matio#35]
Hi,

I use Mat_Open compared to Mat_CreateVer, as typically my mat files contain multiple variables.

In this context, I realized that on multiple executions of a code, its associated mat file grows, as if the implicated variables were appended instead of replaced by their new values. 

Hope you understand what I mean. Please let me know otherwise, and I will try to clarify this further.

Very useful library btw, thanks!

**Comment by tbeu** [comment]
If you call Mat_VarWrite twice on the same variable it gets appended if the MAR-file is opened by Mat_Open. You need to call Mat_VarDelete to delete the variable. See [ModelicaIO_writeRealMatrix](https://github.com/svn2github/Modelica_StandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaIO.c#L332-L403) for an example.

**Comment by kupiqu** [comment]
Thanks for your fast response.

Unfortunately, it only works partially in an example of mine, in particular it works for saving a structure but not for a vector, which is weird. I'll try to investigate this a bit more...

**Comment by tbeu** [comment]
OK, let me know if you discover some more details.

**Comment by kupiqu** [comment]
Hi,

I added further controls:

1. to check whether the variables exist, and if so delete it

2. still before writing then I recheck to confirm that the variable is not present anymore

Doing this I saw that Mat_VarDelete only deletes the first variable that is requested but not subsequent ones. Yet the function returns 0 as it if worked correctly.

Any idea/suggestion on how to deal with this?

**Comment by tbeu** [comment]
What about looping over Mat_VarDelete, e.g.,
```c
while (0 == Mat_VarDelete(mat, varname));
```

**Comment by kupiqu** [comment]
I just did it, but unfortunately it doesn't work (infinite loop). Then, I think the problem is not that there are multiple copies of a variable in a mat file, but that somehow Mat_VarDelete does not do its job. Well it does it for the first variable, but somehow not for the next ones.

Would it be hard for you to try to reproduce this issue? It might be that there is sth wrong with my setup, but I cannot foresee what it could be...

**Comment by tbeu** [comment]
I'll debug it and let you know.

**Comment by kupiqu** [comment]
Thanks!

**Comment by tbeu** [comment]
Sorry, I was wrong. `Mat_VarDelete(mat, varname)` deletes all occurences of varname in the MAT-file. No need to loop.

**Comment by kupiqu** [comment]
Ok, great. 

But what about if you delete two variables, first varname1: Mat_VarDelete(mat, varname1), and then varname2: Mat_VarDelete(mat, varname2).

Have you been able to check if in this case Mat_VarDelete(mat, varname2) works as it is expected?
As far as I could see, Mat_VarDelete(mat, varname2) returns 0 but does not actually delete varname2.

Thanks for helping

**Comment by tbeu** [comment]
Just to be sure: which MAT-file version is it and how many variables are in the MAT-file?

**Comment by kupiqu** [comment]
Ok, I think I figured it out.

The trick seems to be that each Mat_VarDelete (for each variable deletion) needs to be in between of  Mat_Open and Mat_Close, whereas multiple Mat_VarWrite may appear together (for several variables).

**Comment by kupiqu** [comment]
I used this example to test this out

`#include <matio.h>
#include <iostream>
#include <fstream>

// Save as example.cpp and compile with: g++ example.cpp -o example -lmatio
// Then just execute it with: ./example
// Check how the size of test.mat does not change with multiple executions
// This is unless Mat_Close and Mat_Open calls around deleteVarIfExists are commented out

bool exists(const char *matFilename);
int deleteVarIfExists(mat_t *mat, const char *varName);

int main(void) {

  double a[250] = {43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0, 43.5, 5432.434, 3.32, 0.0001, 88834.0};

  mat_t *mat;
  matvar_t *matvar1, *matvar2;
  long unsigned dims[2] = {1,250};
  const char *matFilename = "test.mat";

  if (exists(matFilename)) {
    std::cout << "Mat file already exists, opening: " << matFilename << std::endl;
    mat = Mat_Open(matFilename,MAT_ACC_RDWR);
  }
  else {
    std::cout << "Mat file does not exist, creating: " << matFilename << std::endl;
    mat = Mat_CreateVer(matFilename, NULL, MAT_FT_DEFAULT);
  }

  const char *varName1 = "vec1";
  const char *varName2 = "vec2";
  int resDel;

  matvar1 = Mat_VarCreate(varName1,MAT_C_DOUBLE,MAT_T_DOUBLE,2,dims,a,0);
  matvar2 = Mat_VarCreate(varName2,MAT_C_DOUBLE,MAT_T_DOUBLE,2,dims,a,0);

  Mat_VarWrite(mat, matvar1, MAT_COMPRESSION_ZLIB);
  Mat_VarWrite(mat, matvar2, MAT_COMPRESSION_ZLIB);

  Mat_Close(mat);

  mat = Mat_Open(matFilename,MAT_ACC_RDWR);
  resDel = deleteVarIfExists(mat, varName1);

  Mat_Close(mat);

  mat = Mat_Open(matFilename,MAT_ACC_RDWR);
  resDel = deleteVarIfExists(mat, varName2);

  Mat_Close(mat);

  mat = Mat_Open(matFilename,MAT_ACC_RDWR);
  Mat_VarWrite(mat, matvar1, MAT_COMPRESSION_ZLIB);
  Mat_VarWrite(mat, matvar2, MAT_COMPRESSION_ZLIB);

  Mat_VarFree(matvar1);
  Mat_VarFree(matvar2);
  Mat_Close(mat);

  return 0;
}

bool exists(const char *matFilename) {
  if (FILE *file = fopen(matFilename, "r")) {
    fclose(file);
    return true;
  }
  else {
    return false;
  }
}

int deleteVarIfExists(mat_t *mat, const char *varName) {
  matvar_t *matvar = Mat_VarReadInfo(mat, varName);
  int resDel;

  std::cout << "matvar: " << matvar << std::endl;
  if (matvar != NULL) {
    std::cout << "Variable exists: " << varName << std::endl;
    int resDel = Mat_VarDelete(mat, varName);
    matvar = Mat_VarReadInfo(mat, varName);
    if (matvar != NULL) {
      std::cout << "Variable still exists: " << varName << std::endl;
    }
  }
  return resDel;
}
`

**Comment by kupiqu** [comment]
I think this basically solves my issue. 

In my code I wrap now each deletion within open and close instructions, and it works just fine.

From here, it would be nice to either document it somewhere for other potential people that might be interested, or perhaps, as a feature request, adapt the matio code to do this within its library.

Thanks for your help!

**Comment by tbeu** [comment]
I debugged it. Mat_Close is only necessary after the calls of Mat_VarWrite.

See https://gist.github.com/tbeu/09ec97d53ee0836927da664b1b963671

**Comment by kupiqu** [comment]
That's actually right.

Would it be a possibility that MATIO just reopens the mat file after each write call so final users do not need to worry about this?

**Comment by tbeu** [comment]
I believe 932fded together with calling Mat_Rewind before Mat_VarDelete solves the issue. See https://gist.github.com/tbeu/09ec97d53ee0836927da664b1b963671 for the update. And again Mat_VarReadInfo before Mat_VarDelete is and was superfluous.

**Comment by tbeu** [comment]
You might ask for adding Mat_Rewind to the begin of Mat_VarDelete then.

**Comment by kupiqu** [comment]
That would be great!

Btw, was v7.3 not affected?

**Comment by tbeu** [comment]
Reopen for the moment.

**Comment by tbeu** [comment]
No, v7.3 does not seem to be affected.

**Comment by tbeu** [comment]
Please also check 48b723a and simply replace deleteVarIfExists by Mat_VarDelete in [example.cpp](https://gist.github.com/tbeu/09ec97d53ee0836927da664b1b963671).

**Comment by kupiqu** [comment]
Ideally, a user wouldn't need to worry about deleting in advance, so the
library deals with it efficiently on writing, as happens in matlab/octave.

Would that be considered for MATIO?

**Comment by tbeu** [comment]
Yeah, it already is inconsistent. v7.3 raises an error when adding a variable that already exists. v4 and v5 simply append the variable no matter if it already exists.

**Comment by kupiqu** [comment]
My modest opinion is that the library should be consistent. This means to either implement that 'feature' for version v7.3 as it is in MATLAB, or to raise an error in v4 and v5 as it occurs currently in v7.3 (I don't think this is a bad default, actually).

I know this may break some code, for some users, but it will otherwise confuse other users when moving from one mat version to another, as the library is not consistent.

Perhaps you could document the necessity or not of using Mat_VarDelete to overwrite a variable in an existing mat file.

**Comment by tbeu** [comment]
Cannot add a variable more than once to a v7.3 file as the HDF5 throws the error.

Yes, might raise a warning/error if a variable is added more than once to a v4/v5 MAT file.

**Comment by kupiqu** [comment]
Oh I see. Then I agree, this would be the best.

Thanks

**Comment by kupiqu** [comment]
Not sure what would be better, whether a warning or an error. A warning would still be inconsistent, but would not break any existing code.

Btw, even if hdf5 throws the error, you could still check before writing if the variable exists and, if so, delete it, right? I guess Matlab uses sth like that (but anyways, not asking to do this if you don't think this is the most appropriate behavior, and perhaps it isn't)

**Comment by tbeu** [comment]
Ah, no, I must not delete the variable if it already exists.

**Comment by kupiqu** [comment]
The main problem of a (runtime) warning is that it might be returned, yet the developer might not be aware (e.g., in automatized code). If so, the developer would not realize that this is not the expected way to rewrite a variable, instead it would be recommended first to delete it and then write.

**Comment by kupiqu** [comment]
About the hdf5, I meant inside the Mat_VarWrite function, checking if the variable already exists. But perhaps this is not proper for a reason that currently escapes to my comprehension. Could you please explain why this shouldn't be done? Thanks

**Comment by tbeu** [comment]
Proposal: Inside Mat_VarWrite, check if variable name already exists and issue a warning in this case.

**Comment by kupiqu** [comment]
That sounds good to me, but what would be next, to rewrite the variable or not? I think both options may be equally good if all MAT versions behave the same way.

If the variable is not finally written, the warning would say so and why, right?
