### ISSUE TITLE
configure does not work with --enable-debug

### ISSUE THREAD

**Issue by CaptainPaule** [tbeu/matio#38]
I create two Makefiles with configure.
The first Makefile is created with --enable-debug=no, the secound one with --enable-debug=yes
I diff the files and the only different is a space in the CFLAGS argument.

CFLAGS =  -g -O2
CFLAGS = -g -O2

**Comment by tbeu** [comment]
The --enable-debug flag only has an influence on the NODEBUG define of matioConfig.h.

Try to run `./configure --enable-debug=no CFLAGS="-O3" CPPFLAGS="-DNDEBUG"` for an optimized release build.
