### ISSUE TITLE
I'd like to share an incomplete interface to libmx/libmat using 'matio'

### ISSUE THREAD

**Issue by sgqy** [tbeu/matio#54]
This week I help my classmate to port an algorithm written by MATLAB to an ARM platform.
MATLAB do not have libraries on ARM version, so everything should be a C or C++ source.

With the help of `matio`, finally I made [this](https://gist.github.com/sgqy/2721f1133706d1b3fb5988b07d18f61e).
The code worked fine; 'matio' is a great project. :)

Anyway, I only resolved the link errors, so it is very incomplete and unsafe.

**Comment by tbeu** [comment]
That is a pretty good idea. Do you think, you can make a real repository of it and add some more API functions that Matio supports? For example, I added Mat_GetDir recently.
