### ISSUE TITLE
Have to touch the testsuite.at to make the tests work on MSYS2

### ISSUE THREAD

**Issue by emmenlau** [tbeu/matio#56]
I have just created a matio-package for MSYS2, see https://github.com/Alexpux/MINGW-packages/pull/2296
So far my mileage is pretty good, but in order to make test test suite work, I have to use a strange
workaround: I have to touch `test/testsuite.at` before executing `make check`. Is thee some logic
that uses the file date for something related to the tests? If yes, is there a better, cleaner solution
then to touch the file?

**Comment by tbeu** [comment]
Sorry, I have no idea, since I am not a GNU tools expert.
