### ISSUE TITLE
Is there a Java interface?

### ISSUE THREAD

**Issue by emmenlau** [tbeu/matio#57]
Just a friendly question: Is there a Java wrapper or a Java interface for `matio`? I could not find one, only JNMatLib that uses the native Matlab dlls.

**Comment by tbeu** [comment]
There is https://github.com/gradusnikov/jmatio which does not use matio and seems no longer maintained for years.

**Comment by emmenlau** [comment]
Ok maybe I will find some time to try to make a JNI Java wrapper around `matio`.

**Comment by tbeu** [comment]
This would be appreciated.

**Comment by tbeu** [comment]
There also are https://github.com/diffplug/JMatIO and https://github.com/diffplug/matfilerw.
