### ISSUE TITLE
Saving MAT v7.3 without compression

### ISSUE THREAD

**Issue by marbre** [tbeu/matio#62]
With MATLAB R2017a, saving MAT v7.3 without compression was introduced:

https://www.mathworks.com/products/matlab/whatsnew.html
`save Function: Save MAT v7.3 files without compression for improved performance on some storage devices`

Is there additional effort necessary to support this in matio?

**Comment by tbeu** [comment]
Matio supports this feature since long time (by the compression parameter of Mat_VarWrite).

**Comment by marbre** [comment]
Thanks for clarification.

**Comment by tbeu** [comment]
With 355ad4a5e5e16be911182a4672f04681b4e7ec27 it is also considered by the testsuite, both read and write I/O.
