### ISSUE TITLE
The empty struct tests are failing the Matlab portion of the test.

### ISSUE THREAD

**Issue by jfilo** [tbeu/matio#66]
The empty struct tests that use test/matlab/test_write_cell_empty_struct.m (2753, 2827, 2903, and 2979) fail due to a typo in the equality check.  The 'expdata1' on line 5 should be 'expdata'.  

The other empty struct test that uses test/matlab/test_write_empty_struct.m (2708) is also failing, but for different reason.  The file fails to load.  Matlab responds with the error:
 'Unable to read MAT-file /ldisk/matio/matio.git/test/testsuite.dir/2708/test_write_empty_struct.mat. File might be corrupt.'

Note that all 5 of these tests are passing the matio portion of the test.

**Comment by tbeu** [comment]
Thanks for reporting the typo. I appreciate it.
