### ISSUE TITLE
Travis skips MAT version 7.3 testing 

### ISSUE THREAD

**Issue by massich** [tbeu/matio#83]
I was checking the travis builds to check the **mat73** tests for **hdf5** 1.10 and I'm not sure those are executed in the CI. 

For this configuration `"env": "ENABLE_EXTENDED_SPARSE=yes ENABLE_MAT73=yes WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib HDF5_VERSION_DIR=hdf5_1_10_1 MAX_RANK=3"` that leeds to this configuration:

```
   MATIO Configuration Summary       
==============================================================
           C Compiler: gcc-4.8
               CFLAGS: -g -O2 -fprofile-arcs -ftest-coverage 
     Shared Libraries: yes
     Static Libraries: yes
  default MAT version: MAT_FT_MAT5
Features --------------------------------------------
  MAT v7.3 file support: yes
Extended sparse support: yes
Packages --------------------------------------------
                 zlib: -L/home/travis/build/massich/matio/zlib/lib -lz
                 hdf5: -L/home/travis/build/massich/matio/hdf5_1_10_1/hdf5/lib -lhdf5
               MATLAB: 
```

the tests show as skipped in travis: 

```sh
2830: Write 2D double array                           skipped (mat73_write.at:30)
2831: Write 2D single array                           skipped (mat73_write.at:41)
2832: Write 2D int64 array                            skipped (mat73_write.at:53)
2833: Write 2D uint64 array                           skipped (mat73_write.at:65)
2834: Write 2D int32 array                            skipped (mat73_write.at:76)
2835: Write 2D uint32 array                           skipped (mat73_write.at:87)
2836: Write 2D int16 array                            skipped (mat73_write.at:98)
2837: Write 2D uint16 array                           skipped (mat73_write.at:109)
```

(see [here](https://travis-ci.org/tbeu/matio/jobs/351195638#L4530))

I've been trying to trigger them myself [here](https://travis-ci.org/massich/matio/branches) but I didn't manage.

**Comment by massich** [comment]
When testing manually I get no output

```sh
$./test/test_mat write_2d_numeric -v 7.3
$
```

**Comment by tbeu** [comment]
This is due the missing MATLAb application. Please see https://github.com/tbeu/matio/blob/fa95add9eeef8d3215f1de210cd4f0e490b677d4/test/mat73_write.at#L30 and check again the [Readme](https://github.com/tbeu/matio#224-testsuite).

**Comment by tbeu** [comment]
> When testing manually I get no output

This is the expected behaviour, as the testsuite is configured to consider any output to stdout or stderr as error.

**Comment by massich** [comment]
indeed
